In [1]:
import torch
import numpy as np

## Tensor initialization
#### Directly fromd data
The data type is automatically inferred.

In [5]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data.data.dtype)

torch.int64


#### from a NumPy array

In [6]:
np_data=np.array(data)
x_np=torch.from_numpy(np_data)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

#### from another data
The new tensor ratains the properties(shape,datatype) of the argument tensor,unless explicitly overridden.

In [8]:
x_ones=torch.ones_like(x_data)
print(f"One Tensor:\n {x_ones} \n")
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

One Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3399, 0.8319],
        [0.1489, 0.8412]]) 



#### with random or constant values
'shape' is a tuple of tensor dimensions.In the functions below,it detemines the dimensionality of the output tensor.

In [10]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.1447, 0.8812, 0.9861],
        [0.7312, 0.0335, 0.0382]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes
Tensor attributes describe their shape,datatype,and the device on which they are stored.


In [11]:
tensor=torch.rand(3,4)
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")


Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


## Tensor Operations
over 100 tensor operations,including transposing,indexing,slicing,mathmatical operations,line algebra,random sampling,and more are comprehensively described here.
